### PR TITLE
Fixed a bug, where wss implies tls client authentication

### LINKED ISSUE #387: TypeError: Cannot read property 'ca' of undefined
in `lib/transport/websocket.js`:

```js
         if (self._options.url.startsWith('wss://')) {
            // Using TLS
            // Only using the known working flags in the options.
            // https://nodejs.org/api/https.html#https_https_request_options_callback
            options.ca = self._options.tlsConfiguration.ca;
            options.cert = self._options.tlsConfiguration.cert;
            options.key = self._options.tlsConfiguration.key;
            options.rejectUnauthorized = false;
         }
```
please provide a default, if I comment out these tlsConfig lines the connect does work

### PR DESCRIPTION
**Pull request by johannwagner**
Fixes #387

### CODE REVIEW

File: lib/transport/websocket.js [hunk 1]
```diff
@@ -122,16 +122,27 @@ Factory.prototype.create = function () {
             options.protocol = protocols;
          }
 
-         if (self._options.url.startsWith('wss://')) {
+         if (
+            self._options.url.startsWith('wss://') &&
+            self._options.tlsConfiguration &&
+            self._options.tlsConfiguration.ca &&
```
Comment (oddjobz) [inline lib/transport/websocket.js]: Mmm, do you need these last three lines? I think the error is trying to access an attribute inside a null, i.e. if tlsConfiguration is none, but assuming tlsConfiguration is set, .ca, .auth etc should return null rather than erroring, which should be ok?

Comment (johannwagner) [reply lib/transport/websocket.js]: I don't have a specific reason for this, but if you specify a tlsConfiguration, it should contain all those three items, otherwise it won't work. If not, there is a message in the logs, that TLS client authentication was not used due to invalid options.

**Comment by davidtaboas** [comment]
Is there anything new with this?

File: lib/transport/websocket.js (hunk 1 above)
Comment (om26er) [reply lib/transport/websocket.js]: ok, so I think we can be a little more explicit with messaging there. We should first check if `tlsConfiguration` was provided, if it was, we may then evaluate if all its required parameters were provided as well, in case a parameter is missing we should actually log that, so that it becomes easy for anyone using the library to know why TLS is not being used.

**Comment by johannwagner** [comment]
IMHO, this is a relativly critical bug and should be fixed. 
We can add more logging and explaining texts later on.

**Comment by om26er** [comment]
@johannwagner I understand its important but I think we can use the moment to improve the logging a bit. If you are fine I can quickly create a PR against your branch to implement the above suggestion of mine and then we can land it.

**Comment by johannwagner** [comment]
I am completly fine with this, feel free :ok_hand: 
Thanks in Advance :tada:

**Comment by om26er** [comment]
Landed the change, thanks for the bug fix and sorry that took so long.
